sitename: Codes without Borders
title: "Codes Without Borders"
description: "Building The Next Generation Of Nigerian Coders!"
url: "http://codeswithoutborders.org"
baseurl: ''

gems:
  - jekyll-sitemap
