sitename: Codes without Borders
title: Codes Without Borders
description: "Raising The Next Generation Of Nigerian Programmers!"
url: "http://codeswithoutborders.org"
baseurl: '/'
email: feedback@codeswithoutborders.org

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f05f40
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CodesWB
  - title: facebook
    url: https://web.facebook.com/Codes-Without-Borders-878700232238017/
  - title: instagram
    url: https://www.instagram.com/codeswithoutborders/


# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag